[package]
name = "thruster-bin"
version = "0.1.0"
authors = ["Pete Mertz <peter.s.mertz@gmail.com>"]

[dependencies]
futures = "0.1"
serde = "1.0.24"
serde_json = "1.0.8"
serde_derive = "1.0.24"
thruster = { version = "0.5.0-beta3" }
tokio = "0.1.3"
